-- ============================================
-- PRODUCTOS
-- ============================================
CREATE TABLE public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nombre text NOT NULL,
  costo_individual numeric NOT NULL,
  costo_mayoreo numeric NOT NULL,
  material text,
  activo boolean NOT NULL DEFAULT true
);

-- ============================================
-- TECNICAS_IMPRESION
-- ============================================
CREATE TABLE public.tecnicas_impresion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nombre text NOT NULL,
  costo_por_pieza numeric NOT NULL DEFAULT 0,
  minimo_piezas integer NOT NULL DEFAULT 1,
  notas text,
  activo boolean NOT NULL DEFAULT true
);

-- ============================================
-- COTIZACIONES
-- ============================================
CREATE TABLE public.cotizaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  cliente_id bigint NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
  estado text NOT NULL DEFAULT 'cotizado',
  total numeric NOT NULL DEFAULT 0,
  anticipo numeric NOT NULL DEFAULT 0,
  fecha_entrega date,
  notas text
);

-- ============================================
-- ITEMS_COTIZACION
-- ============================================
CREATE TABLE public.items_cotizacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  cotizacion_id bigint NOT NULL REFERENCES public.cotizaciones(id) ON DELETE CASCADE,
  producto_id bigint NOT NULL REFERENCES public.productos(id) ON DELETE RESTRICT,
  tecnica_id bigint NOT NULL REFERENCES public.tecnicas_impresion(id) ON DELETE RESTRICT,
  cantidad integer NOT NULL,
  talla text,
  color text,
  precio_unitario numeric NOT NULL,
  subtotal numeric NOT NULL
);